version: "3.9"

services:
  mysql:
    image: "mysql:8.0.27"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql/password"
    secrets:
      - source: mysql
        target: mysql/password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
    configs:
      - source: db_init
        target: /docker-entrypoint-initdb.d/database.sql
    ports:
      - "3306:3306"

  blagafac:
    # image: "https://github.com/armadias/bottlenovole#main"
    build:             
      context: Serveur
      dockerfile: Dockerfile
    secrets:
      - source: mysql
        target: mysql/password
    ports:
      - 3000:3000
    depends_on:
      - mysql

secrets:
  mysql:
    file: ./mysql_password.txt

configs:
  db_init:
    file: ./database.sql
