apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottlenovoleblagafac-deployment
  labels:
    app: bottlenovoleblagafac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bottlenovoleblagafac
  template:
    metadata:
      labels:
        app: bottlenovoleblagafac 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/bottlenovole_blagafac:latest
        ports:
        - containerPort: 3000