# BottleNovole-Blagafac: Service
apiVersion: v1
kind: Service
metadata:
  name: bottlenovoleblagafac-service
spec:
  selector:
    app: bottlenovoleblagafac
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110