# BottleNovole-Blagafac: Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottlenovoleblagafac-deployment
  labels:
    app: bottlenovoleblagafac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bottlenovoleblagafac
  template:
    metadata:
      labels:
        app: bottlenovoleblagafac 
    spec:
      containers:
      - name: bottlenovoleblagafac
        image: follietm/bottlenovole_blagafac:latest
        env:
            - name: dtb_password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
        ports:
        - containerPort: 3000