# MySQL: Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: bottlenovoleblagafac
    role: db
spec:
  selector:
    app: bottlenovoleblagafac
    role: db
  ports:
  - port: 3306
    targetPort: 3306
